# Generated by Django 5.0.1 on 2024-06-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='soatlar', max_length=31)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
