# Generated by Django 5.0.1 on 2024-12-13 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouses', '0002_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='warehouse',
        ),
    ]
